WITH BANNED AS (
    select REQUEST_AT, COUNT(*) AS CNT
    from trips A
    JOIN USERS CLIENT
    ON A.CLIENT_ID = CLIENT.USERS_ID
    JOIN USERS DRIVER
    ON A.DRIVER_ID = DRIVER.USERS_ID
    WHERE (CLIENT.banned  = 'YES' OR DRIVER.banned  = 'YES') 
    GROUP BY REQUEST_AT),
CANCEL_NOBANNED AS (
    SELECT REQUEST_AT, COUNT(*) AS CNT
    FROM TRIPS A
    JOIN USERS CLIENT
    ON A.CLIENT_ID = CLIENT.USERS_ID
    JOIN USERS DRIVER
    ON A.DRIVER_ID = DRIVER.USERS_ID
    WHERE CLIENT.banned  = 'NO' AND DRIVER.banned  = 'NO' AND STATUS LIKE 'CANCELLED%'
    GROUP BY REQUEST_AT),
TOTAL_JOB AS (
    SELECT REQUEST_AT, COUNT(*) AS CNT
    FROM TRIPS
    GROUP BY REQUEST_AT)
SELECT A.REQUEST_AT AS Day
      ,ROUND((CONVERT(FLOAT,ISNULL(C.CNT,0)) / (A.CNT-ISNULL(B.CNT,0))) , 2) AS 'Cancellation Rate'
FROM TOTAL_JOB A
LEFT JOIN BANNED B
  ON A.REQUEST_AT = B.REQUEST_AT
LEFT JOIN CANCEL_NOBANNED C
  ON A.REQUEST_AT = C.REQUEST_AT
WHERE (A.REQUEST_AT BETWEEN '2013-10-01' AND '2013-10-03')
  AND (A.CNT-ISNULL(B.CNT,0)) <> 0