WITH EXISTS_DATA AS (
    SELECT B.ID, NAME, SUM(DISTANCE) AS TRAVELLED_DISTANCE
    FROM RIDES A
    JOIN USERS B
      ON A.USER_ID = B.ID
    GROUP BY B.ID, NAME),
NOT_EXISTS_DATA AS (
    SELECT ID, NAME, 0 AS TRAVELLED_DISTANCE
    FROM USERS A
    WHERE ID NOT IN (SELECT ID FROM EXISTS_DATA)
)
SELECT *
FROM (
    SELECT NAME, TRAVELLED_DISTANCE
    FROM EXISTS_DATA
    UNION ALL
    SELECT NAME, TRAVELLED_DISTANCE
    FROM NOT_EXISTS_DATA
) S
ORDER BY TRAVELLED_DISTANCE DESC, NAME