/* Write your T-SQL query statement below */
SELECT ACTIVITY_DATE AS DAY, COUNT(*) AS ACTIVE_USERS
FROM (
SELECT ACTIVITY_DATE,USER_ID
FROM ACTIVITY
WHERE ACTIVITY_DATE BETWEEN DATEADD(DAY,-29,'2019-07-27') AND '2019-07-27'
GROUP BY ACTIVITY_DATE,USER_ID) S
GROUP BY ACTIVITY_DATE