WITH NAME_LIST AS (
SELECT DISTINCT SELL_DATE,
STUFF((
             SELECT DISTINCT ',' + PRODUCT
             FROM    ACTIVITIES b 
             WHERE   b.SELL_DATE = a.SELL_DATE
             FOR XML PATH('')
        ),1,1,'') AS PRODUCTS 
FROM ACTIVITIES a
),
SELL_COUNT AS (
    SELECT SELL_DATE,COUNT(*) NUM_SOLD
    FROM (
        SELECT DISTINCT SELL_DATE, PRODUCT
        FROM ACTIVITIES ) S
    GROUP BY SELL_DATE
)
SELECT A.SELL_DATE, NUM_SOLD, PRODUCTS
FROM NAME_LIST A
JOIN SELL_COUNT B
  ON A.SELL_DATE = B.SELL_DATE
ORDER BY SELL_DATE