/* Write your T-SQL query statement below */

WITH BUYER_LIST AS (
    SELECT BUYER_ID
    FROM ORDERS
    WHERE ORDER_DATE BETWEEN '2019-01-01' AND '2019-12-31'
)
SELECT BUYER_ID, JOIN_DATE, COUNT(*) AS 'ORDERS_IN_2019'
FROM BUYER_LIST A
JOIN USERS B
  ON A.BUYER_ID = B.USER_ID
GROUP BY BUYER_ID, JOIN_DATE
UNION
SELECT USER_ID, JOIN_DATE, 0
FROM USERS
WHERE USER_ID NOT IN (SELECT BUYER_ID FROM BUYER_LIST)