/* Write your T-SQL query statement below */
SELECT NAME
FROM SALESPERSON
WHERE NAME NOT IN (
SELECT DISTINCT A.NAME
FROM SALESPERSON A
LEFT JOIN ORDERS B
  ON A.SALES_ID = B.SALES_ID
LEFT JOIN COMPANY C
  ON B.COM_ID = C.COM_ID
WHERE C.NAME = 'RED')