/* Write your T-SQL query statement below */
SELECT A.ID , CASE WHEN B.ID IS NOT NULL THEN B.STUDENT ELSE A.STUDENT END AS STUDENT
FROM SEAT A
LEFT JOIN SEAT B
ON A.ID = B.ID - 1
WHERE A.ID % 2 = 1
UNION
SELECT A.ID , B.STUDENT
FROM SEAT A
LEFT JOIN SEAT B
ON A.ID = B.ID + 1
WHERE A.ID % 2 = 0
